version: '3.8'

# 1. Base comum (configurações compartilhadas)
x-app-base: &app-base
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /mnt/wslg:/mnt/wslg:rw
    - ~/.deepface:/root/.deepface
    - ./src:/app/src
    - ./videos:/app/videos
  environment:
    - DISPLAY=${DISPLAY:-:0}
    - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
    - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
    - PULSE_SERVER=${PULSE_SERVER}
    - TF_USE_LEGACY_KERAS=1
    - PYTHONPATH=/app/src
  network_mode: host
  stdin_open: true
  tty: true
  command: python src/main.py

services:
  # 2. Serviço para Usuários NVIDIA (Default)
  app-gpu:
    <<: *app-base
    image: analise-video-gpu
    container_name: analise-video-app
    build:
      context: .
      args:
        DEVICE_TYPE: gpu # Avisa o Dockerfile para baixar versão CUDA
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]

  # 3. Serviço para Usuários CPU / AMD / Intel
  app-cpu:
    <<: *app-base
    image: analise-video-cpu
    container_name: analise-video-app
    build:
      context: .
      args:
        DEVICE_TYPE: cpu # Avisa o Dockerfile para baixar versão leve
    # Nota: Sem seção 'deploy', o container usa a CPU normalmente.
